### ISSUE TITLE
why the response is truncated?

### ISSUE THREAD

**Issue by ramusbucket** [PromtEngineer/Chat-App-OpenAssistant-API#1]
when I enter my prompt, it gives me truncated output

<img width="647" alt="image" src="https://github.com/PromtEngineer/Chat-App-OpenAssistant-API/assets/3519523/1b06ac8c-23e7-477a-bf58-c2fd904b1c96">

<img width="584" alt="image" src="https://github.com/PromtEngineer/Chat-App-OpenAssistant-API/assets/3519523/ec4ca7d4-795c-4605-bb6f-02c367bb1235">

**Comment by gd03champ** [comment]
Maybe you have to alter the max length of output in config if available

**Comment by PromtEngineer** [comment]
@gd03champ You are right. I have updated the code so now you can set the max_new_token parameter.

**Comment by PromtEngineer** [comment]
please set the max_new_tokens value to the desired number of token. 

`        llm=HuggingFaceHub(repo_id="OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5", model_kwargs={"max_new_tokens":1200})
`
